### ISSUE TITLE
Support for automatically generated transcriptions

### ISSUE THREAD

**Issue by Borchmann** [abuccts/wikt2pron#7]
When pronuntiation is provided by adequate automatic MediaWiki module (eg. [pl-IPA](https://en.wiktionary.org/wiki/Module:pl-IPA) or [ca-IPA](https://en.wiktionary.org/wiki/Module:ca-IPA)), source contains only module name, without word to be transcribed, that is `{{pl-IPA}}` and so on (cf. [API response](https://en.wiktionary.org/w/api.php?action=query&titles=funt&prop=revisions&rvprop=content&format=json&formatversion=2) for Polish word _funt_ or Catalan [_A_](https://en.wiktionary.org/w/api.php?action=query&titles=A&prop=revisions&rvprop=content&format=json&formatversion=2)). 

These cases (at least sometimes, I didn't make extensive tests) receive wrong IPA/X-SAMPA when processed by _wikt2pron_, namely `[{"X-SAMPA": "/\"a.pi/", "IPA": "/\u02c8a.pi/"}]` instead of proper one.

In Catalan it is the case for majority of transcriptions (85%)

**Comment by abuccts** [comment]
Thanks @Borchmann . This issue is fixed in commit b750c80.

It should work for empty templates like `{{pl-IPA}}` and `{{ca-IPA}}` now.
```python
>>> from pywiktionary import Wiktionary
>>> wikt = Wiktionary(XSAMPA=True)
# funt in Polish
>>> wikt.lookup("funt")["Polish"]
[{'IPA': 'funt', 'X-SAMPA': 'funt', 'lang': 'pl'}]
# A in Catalan
>>> wikt.lookup("A")["Catalan"]
[{'IPA': '/ˈa/', 'X-SAMPA': '/"a/', 'lang': 'ca'}]
```

Please feel free to reopen this issue if you have any other questions.
